on: 
  push:
    branches:
      - forked_fiskebot 

env:
  DOCKER_IMAGE: ghcr.io/team-europe/fiskebot

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          docker build -t ${{ env.DOCKER_IMAGE }} -f Dockerfile .
      - run: |
          docker push ${{ env.DOCKER_IMAGE }}